name: Build and Publish Docker Image

# Déclencheur : Un push sur la branche 'main'
on:
  push:
    branches: ['main']

# Variables d'environnement
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Permissions nécessaires pour écrire dans le registre de paquets
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Se connecter au registre GitHub (GHCR)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Générer les métadonnées (tags, labels)
      # Cela permet de gérer proprement les majuscules/minuscules et les versions
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      # 4. Construire et Pousser l'image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
